project:
  type: website
  output-dir: docs
  preview:
    port: 4200

website:
  site-url: https://www.beyondshunya.com
  title: "Beyond Shunya"
  twitter-card: true
  navbar:
    pinned: false
    left:
      - text: "Blog"
        href: blog.qmd
      - text: "Bookshelf"
        href: "bookshelf.qmd"
  page-footer: 
    right: 
      - icon: github
        href: https://github.com/Realsid
      - icon: twitter 
        href: https://x.com/sid_on_x
      - icon: linkdin
        href: https://www.linkedin.com/in/sid-on-in

format:
  html:
    theme: 
      dark: [darkly, custom.scss]
      light: [flattly, custom.scss]
    css: styles.css
    toc: true
execute:
  freeze: auto