project:
  type: website
  output-dir: docs
  preview:
    port: 4200
extensions:
  - socials

website:
  site-url: https://www.beyondshunya.com
  title: "Beyond Shunya"
  navbar:
    pinned: false
    search: false
    title: "Beyond Shunya"
    left:
      - text: "posts"
        href: "posts.qmd"
      - text: "bookshelf"
        href: "bookshelf.qmd"
  page-footer: 
    right: 
      - icon: github
        href: https://github.com/Realsid
      - icon: twitter 
        href: https://x.com/sid_on_x
      - icon: linkdin
        href: https://www.linkedin.com/in/sid-on-in

format:
  html:
    theme: 
      - litera
      - custom.scss
    css: styles.css
    toc: true
    filters:
      - socials
execute:
  freeze: auto